# Generated by Django 5.1.1 on 2024-09-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_communication_payment_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationForResident',
        ),
    ]
