# Generated by Django 5.1.1 on 2024-10-13 14:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_registration_registrationforresident'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='contact_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
